### ISSUE TITLE
How to output a file ? 

### ISSUE THREAD

**Issue by dridk** [genepi/cloudgene#52]
I don't know how to specify the output filename ! Using type = local_file create a file output inside the output folder.  But I want a file named "merged.vcf" . 

```
workflow:
    steps:
      - name: Step1 
        cmd: /bin/bash run.sh $input > $output
        bash: true

    inputs:
      - id: input
        description: a zip folder with many VCF 
        type: local_file

    outputs:
      - id: output
        description: Merged vcf file 
        type: local_file
````
